services:
  - type: web
    name: trim-video-trimmer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
